name: flutter_easyloading
description: Easy Loading
version: 1.0.0
homepage: https://github.com/vishalsigmasolve/flutter_easyloading

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1
  back_button_interceptor: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
