name: flutter_easyloading
description: Easy Loading
version: 1.0.2

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1
  back_button_interceptor: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
